### ISSUE TITLE
Line scrolling does not seem to function.

### ISSUE THREAD

**Issue by JimPettis** [PooSham/atom-scroll-without-moving-cursor#4]
As far as I can tell, the line-scrolling function does not work. I try "Alt-UP" and "Alt-DOWN" and get nothing. The "Alt-PAGE UP" and "Alt-PAGE DOWN" function seems to work fine.

**Comment by PooSham** [comment]
I'm sorry, I don't use atom anymore and thus don't keep this plugin up to date.
